### ISSUE TITLE
Errors when compile in Ubuntu 14.04

### ISSUE THREAD

**Issue by letienhung** [xianyi/OpenBLAS#666]
I use Intel Xeon E5-2609 v2 and can compile the lastest version of OpenBLAS without problems in Windows 10 x64. Just installed Ubuntu 14.04 x64 as the second OS and now I can't compile OpenBLAS anymore. Here is the error I got:

gemv.c: In function ‘sgemv_’:
gemv.c:232:41: error: ‘GEMM_MULTITHREAD_THRESHOLD’ undeclared (first use in this function)
   if ( MNK <= (24.0 \* 24.0  \* (double) (GEMM_MULTITHREAD_THRESHOLD_GEMM_MULTITHREAD_THRESHOLD) )  )
                                         ^
gemv.c:232:41: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *_\* [sgemv.o] Error 1
make[1]: Leaving directory `/media/letienhung/DATA/Softs/Educations/Libraries/LAPACK/OpenBLAS-0.2.14/interface'
make: **\* [libs] Error 1

I tried to run with TARGET=SANDYBRIDGE but didn't success. I don't see Ivy Bridge in the list of supported CPUs. Can anyone help me? Thanks :(

**Comment by xianyi** [comment]
OpenBLAS supports ivy bridge.

```
make clean
make
```
