### ISSUE TITLE
libopenblas.so.0.3: undefined reference to `gotoblas_NEOVERSEN2' 0.3.23

### ISSUE THREAD

**Issue by torehl** [xianyi/OpenBLAS#4121]
During the build on Ubuntu 18.04LTS aarch64, I get the following error:

```
[ 89%] Linking C executable openblas_utest
../lib/libopenblas.so.0.3: undefined reference to `gotoblas_NEOVERSEN2'
../lib/libopenblas.so.0.3: undefined reference to `gotoblas_NEOVERSEV1'
collect2: error: ld returned 1 exit status
utest/CMakeFiles/openblas_utest.dir/build.make:407: recipe for target 'utest/openblas_utest' failed
make[2]: *** [utest/openblas_utest] Error 1
CMakeFiles/Makefile2:1048: recipe for target 'utest/CMakeFiles/openblas_utest.dir/all' failed
make[1]: *** [utest/CMakeFiles/openblas_utest.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
torel@n005:~/workspace/OpenBLAS/0.3.23/OpenBLAS-0.3.23/Build-aarch64$ 
```

OS: 

```
torel@n005:~/workspace/OpenBLAS/0.3.23/OpenBLAS-0.3.23/Build-aarch64$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

Commandline: 

`cmake .. -DCMAKE_INSTALL_PREFIX=/cm/shared/apps/openblas/dynamic/0.3.23 -DBUILD_SHARED_LIBS=ON -DBINARY=64 -DDYNAMIC_ARCH=1 -DUSE_THREAD=1 `

Error: 

```
[100%] Building Fortran object lapack-netlib/TESTING/LIN/CMakeFiles/xlintstc.dir/slaord.f.o
[100%] Linking Fortran executable xlintsts
[100%] Linking Fortran executable xlintstz
[100%] Linking Fortran executable xeigtstd
../../../lib/libopenblas.so.0.3: undefined reference to `gotoblas_NEOVERSEN2'
../../../lib/libopenblas.so.0.3: undefined reference to `gotoblas_NEOVERSEV1'
collect2: error: ld returned 1 exit status
lapack-netlib/TESTING/LIN/CMakeFiles/xlintsts.dir/build.make:4463: recipe for target 'lapack-netlib/TESTING/LIN/xlintsts' failed
make[2]: *** [lapack-netlib/TESTING/LIN/xlintsts] Error 1
CMakeFiles/Makefile2:1904: recipe for target 'lapack-netlib/TESTING/LIN/CMakeFiles/xlintsts.dir/all' failed
make[1]: *** [lapack-netlib/TESTING/LIN/CMakeFiles/xlintsts.dir/all] Error 2
../../../lib/libopenblas.so.0.3: undefined reference to `gotoblas_NEOVERSEN2'
../../../lib/libopenblas.so.0.3: undefined reference to `gotoblas_NEOVERSEV1'
collect2: error: ld returned 1 exit status
lapack-netlib/TESTING/LIN/CMakeFiles/xlintstz.dir/build.make:5217: recipe for target 'lapack-netlib/TESTING/LIN/xlintstz' failed
make[2]: *** [lapack-netlib/TESTING/LIN/xlintstz] Error 1
CMakeFiles/Makefile2:1828: recipe for target 'lapack-netlib/TESTING/LIN/CMakeFiles/xlintstz.dir/all' failed
make[1]: *** [lapack-netlib/TESTING/LIN/CMakeFiles/xlintstz.dir/all] Error 2
../../../lib/libopenblas.so.0.3: undefined reference to `gotoblas_NEOVERSEN2'
../../../lib/libopenblas.so.0.3: undefined reference to `gotoblas_NEOVERSEV1'
collect2: error: ld returned 1 exit status
lapack-netlib/TESTING/EIG/CMakeFiles/xeigtstd.dir/build.make:2773: recipe for target 'lapack-netlib/TESTING/EIG/xeigtstd' failed
make[2]: *** [lapack-netlib/TESTING/EIG/xeigtstd] Error 1
CMakeFiles/Makefile2:2118: recipe for target 'lapack-netlib/TESTING/EIG/CMakeFiles/xeigtstd.dir/all' failed
make[1]: *** [lapack-netlib/TESTING/EIG/CMakeFiles/xeigtstd.dir/all] Error 2
[100%] Linking Fortran executable xlintstc
../../../lib/libopenblas.so.0.3: undefined reference to `gotoblas_NEOVERSEN2'
../../../lib/libopenblas.so.0.3: undefined reference to `gotoblas_NEOVERSEV1'
collect2: error: ld returned 1 exit status
lapack-netlib/TESTING/LIN/CMakeFiles/xlintstc.dir/build.make:5217: recipe for target 'lapack-netlib/TESTING/LIN/xlintstc' failed
make[2]: *** [lapack-netlib/TESTING/LIN/xlintstc] Error 1
CMakeFiles/Makefile2:1638: recipe for target 'lapack-netlib/TESTING/LIN/CMakeFiles/xlintstc.dir/all' failed
make[1]: *** [lapack-netlib/TESTING/LIN/CMakeFiles/xlintstc.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
torel@n005:~/workspace/OpenBLAS/0.3.23/OpenBLAS-0.3.23/Build-aarch64$
```

Any suggestions?

**Comment by martin-frbg** [comment]
The list of affected kernels suggests it is because your compiler does not support SVE instructions - they should have been automatically dropped from the list (definitely are when building with "make"), looks like there is an error in one of our cmake scripts

**Comment by martin-frbg** [comment]
Ah, CMAKE builds still rely on a compiler version check instead of checking for NO_SVE like the rest of the code :/
Can you please try replacing line 48 in file `cmake/arch.cmake`
https://github.com/xianyi/OpenBLAS/blob/4d0b7fbec04c95c90291938a5974f00673e10e68/cmake/arch.cmake#L48
with a simple `if (NOT NO_SVE)` ? Maybe you have a new enough compiler but too old assembler (binutils) for SVE

**Comment by brada4** [comment]
If you want to have fast package for Neoverse CPU either:
Please read EOL notice and consider upgrading:
https://ubuntu.com//blog/18-04-end-of-standard-support
While no new builds will be provided old "testing" packages for much newer gcc than default are here:
https://launchpad.net/%7Eubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=bionic
