### ISSUE TITLE
Can't install OpenBLAS on 2015th MacBook Pro 13.

### ISSUE THREAD

**Issue by a7744hsc** [xianyi/OpenBLAS#679]
I want to install OpenBLAS on my MacBook Pro 13 (i5-5XXX CPU, intel integrated graphics).I tried to install OpenBLAS form homebrew-science and source code. They both failed with the same error message. 
I googled and found the reason may be the new CPUs( broadwell architecture) 
have not been adapted. Can any one help or give a workaround? 

Part of the Error Message :
printf("#define DLOCAL_BUFFER_SIZE\t%ld\n", (DGEMM_DEFAULT_Q * DGEMM_DEFAULT_UNROLL_N * 2 * 1 * sizeof(double)));
^
getarch_2nd.c:69:50: error: use of undeclared identifier 'CGEMM_DEFAULT_Q'
printf("#define CLOCAL_BUFFER_SIZE\t%ld\n", (CGEMM_DEFAULT_Q * CGEMM_DEFAULT_UNROLL_N * 4 * 2 * sizeof(float)));
^
getarch_2nd.c:69:68: error: use of undeclared identifier 'CGEMM_DEFAULT_UNROLL_N'
printf("#define CLOCAL_BUFFER_SIZE\t%ld\n", (CGEMM_DEFAULT_Q * CGEMM_DEFAULT_UNROLL_N * 4 * 2 * sizeof(float)));
^
getarch_2nd.c:70:50: error: use of undeclared identifier 'ZGEMM_DEFAULT_Q'
printf("#define ZLOCAL_BUFFER_SIZE\t%ld\n", (ZGEMM_DEFAULT_Q * ZGEMM_DEFAULT_UNROLL_N * 2 * 2 * sizeof(double)));
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [getarch_2nd] Error 1
Makefile:131: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail.. Stop.

**Comment by martin-frbg** [comment]
Which version are you trying to install ? 0.2.15 was released this week, anything packaged by third party may still be 0.2.14. ("make clean; make TARGET=HASWELL" would probably work with 0.2.14, I believe 0.2.15 will detect Broadwell automatically)

**Comment by a7744hsc** [comment]
@martin-frbg  Thanks very much.  By using 0.2.15, I works fine.
