### ISSUE TITLE
OpenBLAS: Detecting CPU failed

### ISSUE THREAD

**Issue by tastyminerals** [xianyi/OpenBLAS#1242]
Attempting to install on the **Kaby Lake** laptop:

```
CPU:       Quad core Intel Core i7-7700HQ (-HT-MCP-) cache: 6144 KB 
           clock speeds: max: 3800 MHz 1: 799 MHz 2: 799 MHz 3: 799 MHz 4: 799 MHz 5: 799 MHz 6: 799 MHz
           7: 799 MHz 8: 799 MHz
Graphics:  Card: NVIDIA GP104M [GeForce GTX 1070 Mobile]
           Display Server: X.Org 1.19.3 driver: nvidia Resolution: 1920x1080@60.02hz
           OpenGL: renderer: GeForce GTX 1070/PCIe/SSE2 version: 4.5.0 NVIDIA 375.66
```
Install log:
```
getarch_2nd.c: In function ‘main’:
getarch_2nd.c:12:35: error: ‘SGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function); did you mean ‘XGEMM_DEFAULT_UNROLL_M’?
     printf("SGEMM_UNROLL_M=%d\n", SGEMM_DEFAULT_UNROLL_M);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   XGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:12:35: note: each undeclared identifier is reported only once for each function it appears in
getarch_2nd.c:13:35: error: ‘SGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function); did you mean ‘SGEMM_DEFAULT_UNROLL_M’?
     printf("SGEMM_UNROLL_N=%d\n", SGEMM_DEFAULT_UNROLL_N);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   SGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:14:35: error: ‘DGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function); did you mean ‘SGEMM_DEFAULT_UNROLL_M’?
     printf("DGEMM_UNROLL_M=%d\n", DGEMM_DEFAULT_UNROLL_M);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   SGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:15:35: error: ‘DGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function); did you mean ‘DGEMM_DEFAULT_UNROLL_M’?
     printf("DGEMM_UNROLL_N=%d\n", DGEMM_DEFAULT_UNROLL_N);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   DGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:19:35: error: ‘CGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function); did you mean ‘DGEMM_DEFAULT_UNROLL_M’?
     printf("CGEMM_UNROLL_M=%d\n", CGEMM_DEFAULT_UNROLL_M);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   DGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:20:35: error: ‘CGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function); did you mean ‘CGEMM_DEFAULT_UNROLL_M’?
     printf("CGEMM_UNROLL_N=%d\n", CGEMM_DEFAULT_UNROLL_N);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   CGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:21:35: error: ‘ZGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function); did you mean ‘CGEMM_DEFAULT_UNROLL_M’?
     printf("ZGEMM_UNROLL_M=%d\n", ZGEMM_DEFAULT_UNROLL_M);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   CGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:22:35: error: ‘ZGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function); did you mean ‘ZGEMM_DEFAULT_UNROLL_M’?
     printf("ZGEMM_UNROLL_N=%d\n", ZGEMM_DEFAULT_UNROLL_N);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   ZGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:69:50: error: ‘SGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean ‘SGEMM_DEFAULT_UNROLL_N’?
     printf("#define SLOCAL_BUFFER_SIZE\t%ld\n", (SGEMM_DEFAULT_Q * SGEMM_DEFAULT_UNROLL_N * 4 * 1 *  sizeof(float)));
                                                  ^~~~~~~~~~~~~~~
                                                  SGEMM_DEFAULT_UNROLL_N
getarch_2nd.c:70:50: error: ‘DGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean ‘SGEMM_DEFAULT_Q’?
     printf("#define DLOCAL_BUFFER_SIZE\t%ld\n", (DGEMM_DEFAULT_Q * DGEMM_DEFAULT_UNROLL_N * 2 * 1 *  sizeof(double)));
                                                  ^~~~~~~~~~~~~~~
                                                  SGEMM_DEFAULT_Q
getarch_2nd.c:71:50: error: ‘CGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean ‘DGEMM_DEFAULT_Q’?
     printf("#define CLOCAL_BUFFER_SIZE\t%ld\n", (CGEMM_DEFAULT_Q * CGEMM_DEFAULT_UNROLL_N * 4 * 2 *  sizeof(float)));
                                                  ^~~~~~~~~~~~~~~
                                                  DGEMM_DEFAULT_Q
getarch_2nd.c:72:50: error: ‘ZGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean ‘CGEMM_DEFAULT_Q’?
     printf("#define ZLOCAL_BUFFER_SIZE\t%ld\n", (ZGEMM_DEFAULT_Q * ZGEMM_DEFAULT_UNROLL_N * 2 * 2 *  sizeof(double)));
                                                  ^~~~~~~~~~~~~~~
                                                  CGEMM_DEFAULT_Q
make: *** [Makefile.prebuild:58: getarch_2nd] Error 1
Makefile:123: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail..  Stop.
```

**Comment by martin-frbg** [comment]
Please use either "TARGET=HASWELL" or download a current "develop" snapshot instead of 0.2.19

**Comment by tastyminerals** [comment]
```
(.text+0x49e): undefined reference to `PREFETCHSIZE'
../libopenblas_haswellp-r0.2.20.dev.a(dsymv_U.o):(.text+0x4f4): more undefined references to `PREFETCHSIZE' follow
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:147: dblat2] Error 1
make[1]: *** Waiting for unfinished jobs....
../libopenblas_haswellp-r0.2.20.dev.a(ssymv_U.o): In function `ssymv_U':
(.text+0x2e2): undefined reference to `PREFETCHSIZE'
../libopenblas_haswellp-r0.2.20.dev.a(ssymv_U.o): In function `ssymv_U':
(.text+0x32a): undefined reference to `PREFETCHSIZE'
../libopenblas_haswellp-r0.2.20.dev.a(ssymv_U.o): In function `ssymv_U':
(.text+0x38b): undefined reference to `PREFETCHSIZE'
../libopenblas_haswellp-r0.2.20.dev.a(ssymv_U.o): In function `ssymv_U':
(.text+0x42c): undefined reference to `PREFETCHSIZE'
../libopenblas_haswellp-r0.2.20.dev.a(ssymv_U.o): In function `ssymv_U':
(.text+0x474): undefined reference to `PREFETCHSIZE'
../libopenblas_haswellp-r0.2.20.dev.a(ssymv_U.o):(.text+0x4d6): more undefined references to `PREFETCHSIZE' follow
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:144: sblat2] Error 1
make[1]: Leaving directory '/home/pavel/OpenBLAS/test'
make: *** [Makefile:117: tests] Error 2
```

**Comment by martin-frbg** [comment]
Please do `make clean` before the make just in case there is anything left over from a previous build attempt. Was the first log also from 0.2.20 ?

**Comment by martin-frbg** [comment]
If the problem persits, please post the output of /proc/cpuinfo. (Basically your issue is the same as #1100 so expected to work except for a minimal uncertainty about the automatic detection of this cpu)

**Comment by tastyminerals** [comment]
After `make clean`, `make target=HASWELL` worked without errors and I was able to `sudo make install` the package. 
Thank you for very fast help!

**Comment by martin-frbg** [comment]
Can you please post the model number from /proc/cpuinfo (or just run "./getarch 1" in the build directory first to see if autodetection of your cpu works in 0.2.20) ?

**Comment by tastyminerals** [comment]
```
model		: 158
model name	: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

#define HASWELL
#define L1_CODE_SIZE 16384
#define L1_CODE_ASSOCIATIVE 4
#define L1_CODE_LINESIZE 64
#define L1_DATA_SIZE 8192
#define L1_DATA_ASSOCIATIVE 4
#define L1_DATA_LINESIZE 64
#define L2_SIZE 262144
#define L2_ASSOCIATIVE 8
#define L2_LINESIZE 64
#define ITB_SIZE 2097152
#define ITB_ASSOCIATIVE 0
#define ITB_ENTRIES 8
#define DTB_SIZE 4096
#define DTB_ASSOCIATIVE 4
#define DTB_DEFAULT_ENTRIES 64
#define HAVE_CMOV
#define HAVE_MMX
#define HAVE_SSE
#define HAVE_SSE2
#define HAVE_SSE3
#define HAVE_SSSE3
#define HAVE_SSE4_1
#define HAVE_SSE4_2
#define HAVE_AVX
#define HAVE_FMA3
#define HAVE_CFLUSH
#define NUM_SHAREDCACHE 1
#define NUM_CORES 1
#define CORE_HASWELL
#define CHAR_CORENAME "HASWELL"
```

**Comment by martin-frbg** [comment]
Thanks. Model 158 (in decimal) corresponds to 9E in hexadecimal, which is further split into model code 9, extended model code E (14 in decimal) as far as the logic in cpuid_x86.c is concerned. So plain `make` should have worked as well with 0.2.20dev (as evidenced by the #define HASWELL from `getarch 1`). It is very much likely that the level1 cache size data found by the tool is too small (full cpuinfo output will probably show 32k), that is issue #1232/patch #1236 which I hesitate to commit so shortly before the 0.2.20 release.

**Comment by fusion809** [comment]
I have the same error with my AMD Ryzen 7 2700 processor. What target do I use for it? AMD?

**Comment by martin-frbg** [comment]
Use TARGET=ZEN for now. The detection mechanism has been fixed in the current "develop" branch but there has not yet been a release since then.

**Comment by fusion809** [comment]
Thanks, I don't think I have the option to use the develop branch given that I'm only building this fine package as part of building SageMath (as you may know SageMath's Makefile builds several dependencies of it first, before building SageMath itself).
