### ISSUE TITLE
[ASK] Add NEOVERSEV2 to the list of targets

### ISSUE THREAD

**Issue by Nicoshev** [xianyi/OpenBLAS#5385]
Hello, Neoverse-N1, Neoverse-N2 and Neoverse-V1 are all supported build targets. Would it be possible to add support for Neoverse-V2 ? It is the core architecture used by Nvidia Grace, Amazon's Graviton 4 and Google Axion, among others.

Thanks

**Comment by Mousius** [comment]
You should be able to use `TARGET=NEOVERSEV2` today. It's also supported in `DYNAMIC_ARCH=1` builds using the `NEOVERSEN2` targets kernels in some cases. What isn't working for you?

**Comment by Nicoshev** [comment]
Ok, thanks

**Comment by Nicoshev** [comment]
@Mousius I actually get:

make
DYNAMIC_ARCH=1
NO_AFFINITY=1
SANITY_CHECK=1
TARGET=NEOVERSEV2
-j36
getarch.c:1827:2: error: #error "The TARGET specified on the command line or in Makefile.rule is not supported. Please choose a target from TargetList.txt"
 1827 | #error "The TARGET specified on the command line or in Makefile.rule is not supported. Please choose a target from TargetList.txt"

**Comment by Mousius** [comment]
For `DYNAMIC_ARCH=1` you typically build with a `TARGET=ARMV8` and it dispatches kernels to the appropriate more optimized target.

Unsure why `TARGET=NEOVERSEV2` isn't working though, everything else is in place for that, and I thought it worked before - may just need adding to that `TargetList.txt`

**Comment by Mousius** [comment]
Ah, we need to add it here: https://github.com/OpenMathLib/OpenBLAS/blob/develop/getarch.c#L1499

**Comment by Mousius** [comment]
Ah, in fact, there's a few places to get it to build independently, can likely plug into here: https://github.com/OpenMathLib/OpenBLAS/blob/develop/param.h#L3639

And also can reuse `NEOVERSEN2` here instead of the less optimized `ARMV8SVE`: https://github.com/OpenMathLib/OpenBLAS/blob/develop/kernel/arm64/KERNEL.NEOVERSEV2

**Comment by martin-frbg** [comment]
wait, wasn't there a hack in place to map V2 to (I think) V1 inside getarch ?

**Comment by Nicoshev** [comment]
@Mousius Could it be an addition for OpenBLAS v0.3.31 ? :)

**Comment by martin-frbg** [comment]
NVM this apparently got lost in our discussion on if/how to keep the number of ARM64 targets low (#4445 among others) , there's only the partial support from #4702  (and DYNAMIC_ARCH mapping it to the N2)  but nothing in param.h
