### ISSUE TITLE
Using OpenBlas on Xcode?

### ISSUE THREAD

**Issue by tiger9502** [xianyi/OpenBLAS#193]
Hi, first of all I apologize for being such a noob.

I am trying to get openblas working on my mac osx 10.8.2, xcode 4.6.  I compiled openblas successfully with TARGET=NEHALEM CC=clang, and then did a make PREFIX=... install into my xcode project folder.  In my xcode the library search path include the openblas lib folder, and the "build phases" has link binary with library for both the .a and .dylib files in it.  When I try to compile I get: (in cmath)
semantic issue: templates must have c++ linkage
use of undeclared identifier __X
....
and finally 
Clang LLVM 1.0 error (too many error emitted, stopping now).

Can some good hearted programmer offer me some help?  it might be obvious to some of you, but it has taken me hours to (yet) figure out...
