### PR TITLE
Fix AIX build

### PR DESCRIPTION
**Pull request by ayappanec**
AIX build with OpenXL broke after PR #4944 with the below errors. 

In file included from ../kernel/power/sbgemv_t_vsx.c:31:
In file included from ../kernel/power/sbgemv_common.c:30:
../kernel/power/gemm_common.c:31:18: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
   31 | typedef __vector IFLOAT        vec_bf16;
      | ~~~~~~~~~~~~~~~~ ^
      | int
../common.h:310:16: note: expanded from macro 'IFLOAT'
  310 | #define IFLOAT  bfloat16
      |                 ^
In file included from ../kernel/power/sbgemv_t_vsx.c:31:
In file included from ../kernel/power/sbgemv_common.c:30:
../kernel/power/gemm_common.c:31:18: error: typedef redefinition with different types ('__vector int' (vector of 4 'int' values) vs 'uint16_t' (aka 'unsigned short'))
../common.h:310:16: note: expanded from macro 'IFLOAT'
  310 | #define IFLOAT  bfloat16
      |                 ^
../common.h:265:18: note: previous definition is here
  265 | typedef uint16_t bfloat16;
      |                  ^
In file included from ../kernel/power/sbgemv_t_vsx.c:31:
In file included from ../kernel/power/sbgemv_common.c:30:
../kernel/power/gemm_common.c:31:24: error: expected ';' after top level declarator
   31 | typedef __vector IFLOAT        vec_bf16;
      |                        ^
      |                        ;
../kernel/power/gemm_common.c:72:13: error: unknown type name 'vec_bf16'
   72 | FORCEINLINE vec_bf16 vec_loadN(void *src, BLASLONG n)
      |             ^
      
Looks like vector types will not work with typedef 'ed defines in AIX with OpenXL compiler. 
Also bool type is used in the sbgemv_common_power10.c and needs the explicit include of stdbool.h in AIX.

### CODE REVIEW

File: kernel/power/gemm_common.c [hunk 1]
```diff
@@ -28,7 +28,12 @@
 #define USE_VECTOR_PAIRS
 #endif
 
+#ifdef _AIX
```
Comment (ChipKerchner) [inline kernel/power/gemm_common.c:31]: I think this should be `#if defined(_AIX) && defined(__clang__)` since you are saying it only breaks on OpenXL

**Comment by ChipKerchner** [comment]
There is also an issue with AIX gcc=10.3.  Please hold off merging this until both compilers can be addressed.

File: kernel/power/gemm_common.c [hunk 2]
```diff
@@ -28,7 +28,12 @@
...
+#include<stdbool.h>
+typedef __vector unsigned short vec_bf16;
```
Comment (ChipKerchner) [inline kernel/power/gemm_common.c:33]: I don't think we need a separate typedef for AIX.  I believe the original should work.

**Comment by ayappanec** [comment]
I just addressed the build issues with gcc compiler also.

**Comment by ChipKerchner** [comment]
Looks good to me.

**Comment by ayappanec** [comment]
Thanks for the merge
