### ISSUE TITLE
Failure to build BFLOAT16 functions on Windows

### ISSUE THREAD

**Issue by drtcp** [xianyi/OpenBLAS#3540]
Hello, 
It appears the pre-built binaries do not contain the BFLOAT16 functions declared in `cblas.h` (Windows 64bit)

Also, when I try to build on Windows, carefully following the instructions (https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio) the build fails.
So far, two types of error occur, both for CooperLake. 

```
S:/code/BLAS/OpenBLAS/OpenBLAS-develop/kernel/x86_64/sbgemm_ncopy_16_cooperlake.c(138,2): error: unknown type name 'u_int64_t'; did you mean 'uint64_t'?
        u_int64_t permute_table2[] = {
        ^~~~~~~~~
        uint64_t
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\stdint.h(24,28): note: 'uint64_t' declared here
```

and the second manifests in a macro which appears to be using the AVX512 incorrectly for CooperLake. Hence, this error occurs many times.

```
C:/code/BLAS/OpenBLAS/OpenBLAS-develop/kernel/x86_64/sbgemm_kernel_16x4_cooperlake.c(297,4): error: Register k0 can't be used as write mask
                        MASK_STORE_4X(0, 0, 0); MASK_STORE_4X(0, 0, 1); MASK_STORE_4X(0, 0, 2);
```
This GitHub link seems to provide some relevant info:  https://github.com/golang/go/issues/29893

Would it be possible for you to investigate why Open BLAS fails to build for BFLOAT16 using the Windows build instructions?
I am currently using the following cmake line:

`cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DCMAKE_MT=mt -DBUILD_WITHOUT_LAPACK=yes -DNOFORTRAN=1 -DDYNAMIC_ARCH=ON -DBUILD_BFLOAT16=ON -DCMAKE_BUILD_TYPE=Release`

I have also tried with the cmake line provided in the build instructions, the errors are the same.
I have tried using Visual Studio 2015 and also 2019 (deleting the build folder each time, and starting afresh), the errors are the same.

Any help or guidance you could provide would be very much appreciated. 
The work you people do is truly impressive.

Thank you

**Comment by martin-frbg** [comment]
First looks to be a "harmless" typo that will not show up on platforms that alias the two spelling variants (Linux, Mac, probably BSD as well), seems MSVC headers do not alias u_int64_t to uint64_t.
Second one I'm less sure how to handle - almost looks like an assembler error (picking k0 of all things when the instruction only says k). Found something in the llvm-dev archive where the suggestion was to use "Yk" instead of k ( that would be in all statements of the `_MASK_STORE_C_2nx16` macro starting from line 116, and in `_MASK_STORE_C_16` from line 156).
Unfortunately I do not have Cooperlake hardware to test.

**Comment by drtcp** [comment]
Many thanks for the excellent feedback Martin, it's very much appreciated.

I altered the file `sbgemm_kernel_16x4_cooperlake.c `with the fixes you provided. It compiled.
That allowed the compiler to continue past its limit of 20 errors to reveal more.
The next errors were in the file `sbgemm_microk_cooperlake_template.c` they all appear to be due to calling intrinsic shuffles, e.g. the function `_mm512_shuffle_epi32()` which expects a constant integer rather than an integer. 
Here's the first error (the others are very similar):

`C:/code/BLAS/OpenBLAS/OpenBLAS-develop/kernel/x86_64/sbgemm_microk_cooperlake_template.c(396,35): error: argument to '__builtin_ia32_pshufd512' must be a constant integer
                arrayB_512[i]   = _mm512_shuffle_epi32(arrayB_512[i], SHUFFLE_MAGIC_NO);`

In the file the variable `SHUFFLE_MAGIC_NO` is declared as an integer in various functions.

I altered it to be defined as a constant integer thus:
`#define  SHUFFLE_MAGIC_NO (const int)0x39`

I then deleted the build folder and started again. This allowed the compilation to continue.
Unfortunately I then obtained link errors;

`[71/72] Linking C static library lib\Release\openblas.lib
[72/72] Linking C executable utest\openblas_utest.exe
FAILED: utest/openblas_utest.exe 
cmd.exe /C "cd . && C:\Users\tim\anaconda3\Library\bin\cmake.exe -E vs_link_exe --intdir=utest\CMakeFiles\openblas_utest.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\link.exe /nologo utest\CMakeFiles\openblas_utest.dir\utest_main2.c.obj  /out:utest\openblas_utest.exe /implib:lib\Release\openblas_utest.lib /pdb:utest\openblas_utest.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console  lib\Release\openblas.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK: command "C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\link.exe /nologo utest\CMakeFiles\openblas_utest.dir\utest_main2.c.obj /out:utest\openblas_utest.exe /implib:lib\Release\openblas_utest.lib /pdb:utest\openblas_utest.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console lib\Release\openblas.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:utest\openblas_utest.exe.manifest" 

failed (exit code 1120) with the following output:
openblas.lib(setparam_PRESCOTT.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_PRESCOTT
openblas.lib(setparam_NEHALEM.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_NEHALEM
openblas.lib(setparam_CORE2.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_CORE2
openblas.lib(setparam_BARCELONA.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_BARCELONA
openblas.lib(setparam_SANDYBRIDGE.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_SANDYBRIDGE
openblas.lib(setparam_BULLDOZER.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_BULLDOZER
openblas.lib(setparam_PILEDRIVER.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_PILEDRIVER
openblas.lib(setparam_HASWELL.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_HASWELL
openblas.lib(setparam_STEAMROLLER.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_STEAMROLLER
openblas.lib(setparam_EXCAVATOR.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_EXCAVATOR
openblas.lib(setparam_ZEN.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_ZEN
openblas.lib(setparam_SKYLAKEX.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_SKYLAKEX
openblas.lib(setparam_COOPERLAKE.c.obj) : error LNK2019: unresolved external symbol sbgemm_r referenced in function init_parameter
utest\openblas_utest.exe : fatal error LNK1120: 13 unresolved externals
ninja: build stopped: subcommand failed.`

I did notice that you have added the directive "Fix Compilation for CooperLake on Windows/clang". I am not used to
the etiquette of how this forum/issues WiKi works. Should I stop providing feedback, or is this additional message useful?
Thank you again.

**Comment by martin-frbg** [comment]
This is extremely useful - the issue ticket was automatically closed when I merged the fixes we had come up with yesterday. I will reopen it and try to find out where the missing references come from - possibly something in the cmake build files not matching what the gmake build does

**Comment by drtcp** [comment]
Many thanks Martin, very much appreciated.

**Comment by martin-frbg** [comment]
Bisected to #3364 , which apparently missed defining sbgemm_r for DYNAMIC_ARCH builds. The "const int" issue on the other hand appears to be a problem not seen with gcc.

**Comment by drtcp** [comment]
Hi Martin, unfortunately the link errors are still present:


```
192 warnings generated.
[9354/9355] Linking C static library lib\Release\openblas.lib
[9355/9355] Linking C executable utest\openblas_utest.exe
FAILED: utest/openblas_utest.exe 
cmd.exe /C "cd . && C:\Users\tim\anaconda3\Library\bin\cmake.exe -E vs_link_exe --intdir=utest\CMakeFiles\openblas_utest.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\PROFES~1\VC\Tools\MSVC\1429~1.300\bin\Hostx64\x64\link.exe /nologo utest\CMakeFiles\openblas_utest.dir\utest_main2.c.obj  /out:utest\openblas_utest.exe /implib:lib\Release\openblas_utest.lib /pdb:utest\openblas_utest.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console  lib\Release\openblas.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK: command "C:\PROGRA~2\MICROS~1\2019\PROFES~1\VC\Tools\MSVC\1429~1.300\bin\Hostx64\x64\link.exe /nologo utest\CMakeFiles\openblas_utest.dir\utest_main2.c.obj /out:utest\openblas_utest.exe /implib:lib\Release\openblas_utest.lib /pdb:utest\openblas_utest.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console lib\Release\openblas.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:utest\openblas_utest.exe.manifest" failed (exit code 1120) with the following output:
openblas.lib(setparam_PRESCOTT.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_PRESCOTT
openblas.lib(setparam_NEHALEM.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_NEHALEM
openblas.lib(setparam_CORE2.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_CORE2
openblas.lib(setparam_BARCELONA.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_BARCELONA
openblas.lib(setparam_SANDYBRIDGE.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_SANDYBRIDGE
openblas.lib(setparam_BULLDOZER.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_BULLDOZER
openblas.lib(setparam_PILEDRIVER.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_PILEDRIVER
openblas.lib(setparam_HASWELL.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_HASWELL
openblas.lib(setparam_STEAMROLLER.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_STEAMROLLER
openblas.lib(setparam_EXCAVATOR.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_EXCAVATOR
openblas.lib(setparam_ZEN.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_ZEN
openblas.lib(setparam_SKYLAKEX.c.obj) : error LNK2001: unresolved external symbol sbgemm_small_kernel_b0_tt_SKYLAKEX
utest\openblas_utest.exe : fatal error LNK1120: 12 unresolved externals
ninja: build stopped: subcommand failed.
```

I altered the `kernel/setparam-ref.c` as specified in https://github.com/xianyi/OpenBLAS/pull/3547/files, I added the following code after line 1826
```
#if BUILD_BFLOAT16==1
  TABLE_NAME.sbgemm_r = (((BUFFER_SIZE -
			       ((TABLE_NAME.sbgemm_p * TABLE_NAME.sbgemm_q *  4 + TABLE_NAME.offsetA
				 + TABLE_NAME.align) & ~TABLE_NAME.align)
			       ) / (TABLE_NAME.sbgemm_q *  4) - 15) & ~15);
#endif
```

I have previously altered the const integer(s) in `kernel/x86_64/sbgemm_microk_cooperlake_template.c` using

`#define SHUFFLE_MAGIC_NO (const int)0x39`

Initially I simply added the `const` in front of the `int` declaration. However, that still produced the compile errors.
I therefore used the compiler directive above to force the values to be constant integers. This removed the compiler errors and the `openblas.lib` was built.

I still get the link errors above. Please forgive me if I am being overly enthusiastic, and thank you for this tremendous help.

**Comment by drtcp** [comment]
On a more detailed look at the link errors, it appears that one of the previous errors:

`openblas.lib(setparam_COOPERLAKE.c.obj) : error LNK2019: unresolved external symbol sbgemm_r referenced in function init_parameter`

Has been fixed. Which is not surprising since you added the code to deal with it...

**Comment by martin-frbg** [comment]
Sorry, I am still working on the fix as I find time today besides my regular work commitments.

**Comment by drtcp** [comment]
No need to be sorry Martin, I thank you very much for everything you have done/are doing. I really do appreciate it. Hope work goes well.

**Comment by martin-frbg** [comment]
There's a stray dollar sign in line 681 of kernel/CMakeLists.txt that causes empty definitions for the sources of the various missing sbgemm_small_kernel_b0_tt functions. I've updated the PR accordingly

**Comment by drtcp** [comment]
Wow, excellent, it builds without link errors now:

```
192 warnings generated.
[9366/9367] Linking C static library lib\Release\openblas.lib
[9367/9367] Linking C executable utest\openblas_utest.exe
```
Yipee, now I can run tests...I can't thank you enough Martin.

**Comment by martin-frbg** [comment]
Thank you very much for confirming - my tests so far had been on Linux.

**Comment by drtcp** [comment]
My pleasure, I'll be running some tests on various CPUs comparing single & half precision. I can report the result if you want them.
Thanks again Martin.

**Comment by drtcp** [comment]
Hi Martin.
I have run some tests on the following Windows CPU's:

Alder Lake: 12th Gen Intel i7-12700K 3.61 GHz (approx. 15 times slower)
Westmere EP: Intel® Xeon® Processor X5670 (approx. 6 times slower)
Coffee Lake: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz (approx. 13 times slower)
Sandy Bridge: Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz   3.40 GHz (approx. 5 times slower)
AMD Ryzen Threadripper 3970X 32-Core Processor 3.69 GHz (approx. 14 times slower)

Unfortunately using BFLOAT16 representation produces slower GEMM than single precision. I have put the approximate slow-down factor in brackets after the CPU in the above list.

I used very simply code (shown below, using a single thread only).
I hope this is useful, and thank you again for all the excellent work/help.

```
#include "windows.h"
#include <iostream>
#include <cblas.h>
#include <chrono>

using namespace std;
using namespace std::chrono;

////////////////////////////////////////////////////////////////////////////////
// high resolution timer class
class TestTimer
{
  protected:
    high_resolution_clock::time_point m_start; // saves time point in nanoseconds

  public:
    TestTimer(void)
    {
      m_start = high_resolution_clock::now();
    }

    void Reset(void) { m_start = high_resolution_clock::now(); };

    double nano(void)
    {
      high_resolution_clock::duration lapsed = high_resolution_clock::now() - m_start;
      return (double)lapsed.count();
    }

    double micro(void)
    {
      return nano() * 0.001;
    }

    float ms(void)
    {
      return (float)(micro() * 0.001);
    }

    float s(void)
    {
      return (float)(micro() * 0.000001);
    }

};
////////////////////////////////////////////////////////////////////////////////




/////////////////////////////////////////////////////////
void SetFloatArray(float* p, blasint n, float val)
{
  for (blasint i = 0; i < n; i++) p[i] = val;
}
/////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////
void ToBFLOAT(const float* A, bfloat16* B, blasint n)
{
  cblas_sbstobf16(n, A, 1, B, 1);
}
/////////////////////////////////////////////////////////
void FromBFLOAT(float* A, const bfloat16* B, blasint n)
{
  cblas_sbf16tos(n, B, 1, A, 1);

}
/////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////
void TestBLAS_bFLOAT()
{
  openblas_set_num_threads(1);

  blasint m = 128;
  blasint k = 27;
  blasint n = 64;

  blasint lda = k;
  blasint ldb = n;
  blasint ldc = n;

  // A matrix has (m, k) = (rows, cols)
  blasint A_size = m * k;
  float* A = (float*)malloc(A_size * sizeof(float)); SetFloatArray(A, A_size, 2.0f);

  // B matrix has (k, n) = (rows, cols)
  blasint B_size = k * n;
  float* B = (float*)malloc(B_size * sizeof(float)); SetFloatArray(B, B_size, 2.0f);

  // C matrix has (m, n) = (rows, cols)
  blasint C_size = m * n;
  float* C = (float*)malloc(C_size * sizeof(float)); SetFloatArray(C, C_size, 1.0f);

  // FBLOAT16 matrices
  bfloat16* Ab = (bfloat16*)malloc(A_size * sizeof(bfloat16));
  bfloat16* Bb = (bfloat16*)malloc(B_size * sizeof(bfloat16));
  ToBFLOAT(A, Ab, A_size);
  ToBFLOAT(B, Bb, B_size);


  TestTimer timer;
  double t = 0.0;
  blasint nn = 10000;
  blasint i;

  // do one first to allow lib to find CPU architecture
  cblas_sbgemm(CBLAS_ORDER::CblasRowMajor, CBLAS_TRANSPOSE::CblasNoTrans, CBLAS_TRANSPOSE::CblasNoTrans,
    m, n, k, 1.0f, Ab, lda,
    Bb, ldb,
    1.0f, C, ldc);


  // TEST half precision GEMM
  cout << endl;
  cout << " BFLOAT GEMM" << endl;
  t = 0.0;
  openblas_set_num_threads(1);
  for (i = 0; i < nn; i++)
  {
    SetFloatArray(C, C_size, 1.0f);

    timer.Reset();


    cblas_sbgemm(CBLAS_ORDER::CblasRowMajor, CBLAS_TRANSPOSE::CblasNoTrans, CBLAS_TRANSPOSE::CblasNoTrans,
      m, n, k, 1.0f, Ab, lda,
      Bb, ldb,
      1.0f, C, ldc);

    t += timer.nano();
  }
  t /= (double)nn;

  //cout << "C:" << C << endl;
  cout << "Av time for BFLOAT GEMM = " << t << " nano" << endl;


  // GEMM
  /*
    C := alpha*op(A)*op(B) + beta*C
    where:
      op(X) is one of op(X) = X, or op(X) = XT, or op(X) = XH,
      alpha and beta are scalars,
      A, B and C are matrices:
      op(A) is an m-by-k matrix,
      op(B) is a k-by-n matrix,
      C is an m-by-n matrix.
  */

  cout << endl;
  cout << " GEMM" << endl;
  openblas_set_num_threads(1);
  t = 0.0;
  for (i = 0; i < nn; i++)
  {
    SetFloatArray(C, C_size, 1.0f);

    timer.Reset();

    cblas_sgemm(CBLAS_ORDER::CblasRowMajor, CBLAS_TRANSPOSE::CblasNoTrans, CBLAS_TRANSPOSE::CblasNoTrans,
      m, n, k, 1.0f, A, lda,
      B, ldb,
      1.0f, C, ldc);

    t += timer.nano();
  }
  t /= (double)nn;

  //cout << "C:" << C << endl;
  cout << "Av time for GEMM = " << t << " nano" << endl;


  free(A); free(B); free(C); free(Ab); free(Bb);

}
/////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////
int main()
{
  TestBLAS_bFLOAT();
}
/////////////////////////////////////////////////////////
```

**Comment by martin-frbg** [comment]
Unfortunately this is to be expected on your range of non-AVX512 hardware - right now, optimized x86_64 SBGEMM kernels are only provided for Intel Cooper Lake and Sapphire Rapids cpus (which offer dedicated instruction set support). Minimal BF16 support for older cpus is provided by the "generic" 2x2 blocked SGEMM kernel with added conversions to/from regular float32, so guaranteed to be slower than the respective optimized SGEMM counterparts.
The only other architecture for which actual performant BFLOAT16 support is currently implemented is IBM POWER10.

**Comment by drtcp** [comment]
Sorry for the delay Martin, many thanks for the feedback, much appreciated.

**Comment by drtcp** [comment]
Hi Martin, can Open BLAS make use of the AVX2 on the following CPU?

Intel® Xeon® Processor E5-2630 v4

The Intel ark page says that the CPU has AVX2

Thanks for any info.

**Comment by drtcp** [comment]
Sorry, I meant to also say that I will be using the Linux Open BLAS on that CPU

**Comment by martin-frbg** [comment]
Yes, OpenBLAS should recognize it as Haswell. No advantage for BFLOAT16 though, if that is what you are after

**Comment by drtcp** [comment]
Thanks Martin, much appreciated
