### ISSUE TITLE
In Qt Creator: Armadillo + OpenBLAS compile failed,  but Armadillo + BLAS & LAPACK pass.

### ISSUE THREAD

**Issue by fun4junjun** [xianyi/OpenBLAS#1080]
There are many examples about Armadillo work in Windows. However, they are mainly with Visual Studio. I can hardly find any with Qt Creator.

I did work well with armadillo-7.600.2 + lapack-3.7.0 in Qt Creator. 
The armadillo offers "include" directory, lapackis "Prebuilt dynamic libraries using Mingw", and Qt 5.7.1 for Windows 32-bit (MinGW 5.3.0).
In .pro file, I use 
        INCLUDEPATH += $$PWD\include
        LIBS += -L$$PWD\lib_win32 -lliblapack
        LIBS += -L$$PWD\lib_win32 -llibblas
In main.cpp file, I use 
        #include <iostream>
        #include "armadillo"
        using namespace std;
        using namespace arma;
        ......
It works.

Now, I try to discard BLAS & LAPACK, and choose OpenBLAS.
However, I get many errors when compiling, just as:
        error: undefined reference to `_gfortran_compare_string'

I already tried OpenBLAS v0.2.8, develop, v0.2.15, v0.2.19, etc.  (download Binary package, win32)
        https://sourceforge.net/projects/openblas/files/
The results are same.
In .pro file, I use 
        INCLUDEPATH += $$PWD\include
        LIBS += -L$$PWD\lib -llibopenblas

It seems visual studio can work well. Why qt creator can not? 

Can you give any suggestion? Thanks a lot.

**Comment by martin-frbg** [comment]
Can you try adding -llibgfortran after the -llibopenblas on the LIBS line ? (Looks like the prebuilt lapack contained the fortran runtime library while openblas has it as an external dependency)

**Comment by fun4junjun** [comment]
Thank you very much. It really woks now.
