### ISSUE TITLE
OpenBLAS 3.7.0 test fail when building without CBLAS and LAPACKE

### ISSUE THREAD

**Issue by siko1056** [xianyi/OpenBLAS#2215]
When building OpenBLAS 3.7.0 with

```
make -j3 DYNAMIC_ARCH=1 FC=gfortran NO_CBLAS=1 NO_LAPACKE=1 USE_OPENMP=0
```

The following linker errors with missing LAPACKE and CBLAS functions are obtained.  This can be fully understood, as they are not built by intention.

```
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: test_kernel_regress.o: in function `__ctest_kernel_regress_skx_avx_run':
test_kernel_regress.c:(.text+0xa7): undefined reference to `LAPACKE_dgesvd'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: test_kernel_regress.c:(.text+0x130): undefined reference to `cblas_dgemm'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: test_kernel_regress.c:(.text+0x171): undefined reference to `cblas_dnrm2'
```

This `test_kernel_regress` was introduced in a211bc9b6a6e597a38fc8b8b7ed0b006cb367c46 and should rather check for LAPACKE and CBLAS to be build, not only LAPACK.

Thank you for your help.

# System info

- openSUSE Leap 15.1
- Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz

```
$ uname -a
Linux linux-p86y 4.12.14-lp151.28.10-default #1 SMP Sat Jul 13 17:59:31 UTC 2019 (0ab03b7) x86_64 x86_64 x86_64 GNU/Linux
```

Full build log: 
[OpenBLAS-0.3.7.build.log.tar.gz](https://github.com/xianyi/OpenBLAS/files/3495081/OpenBLAS-0.3.7.build.log.tar.gz)

**Comment by siko1056** [comment]
A fix going in the right direction (works for me) might be as follows:

https://github.com/xianyi/OpenBLAS/blob/303869f5724bb86d722bc32f254a976625ea2046/utest/Makefile#L17-L20

```Makefile
ifneq ($(NO_LAPACK), 1)
OBJS += test_potrs.o
ifneq ($(NO_LAPACKE), 1)
OBJS += test_kernel_regress.o
endif
endif
```

Similar things have to be done in the CMakeLists.txt.

**Comment by brada4** [comment]
You are quite right, tests are added sometimes to barf on some issue, but component (BLAS/CBLAS/LAPACK/RELAPACK/LAPACKE/THREADS) dependencies are not always properly set for reduced function configurations.

**Comment by siko1056** [comment]
@martin-frbg Thank you for the quick fix.
