### ISSUE TITLE
Build errors on apple clang with v0.3.8

### ISSUE THREAD

**Issue by sethrj** [xianyi/OpenBLAS#2431]
I'm trying to build a vanilla OpenBLAS installation on my mac but run into immediate build errors regardless of the build command. Others on my team with similar toolchains hit the same error. I ran `git bisect` (since v0.3.7 builds fine) and found a change to `common_arm64.h` causes the error.

## Build error

```console
$ command make -j1 CC=/usr/bin/clang FC=/usr/local/bin/gfortran 'USE_OPENMP=0' 'USE_THREAD=0' all
In file included from swap.c:40:
In file included from ../common.h:437:
../common_arm64.h:69:38: error: unknown register name 'x2' in asm
                         : "memory", "x2" , "x3", "x4"
                                     ^
```
## First bad commit

```
5f6206fa2de4f533f003379588ca2a8b294e6c2f is the first bad commit
commit 5f6206fa2de4f533f003379588ca2a8b294e6c2f
Author: Martin Kroeker <martin@ruby.chemie.uni-freiburg.de>
Date:   Tue Oct 8 20:13:14 2019 +0200

    Simplify OSX/IOS cross-compilation and add a CI test for it (#2279)

    * Add automatic fixups for OSX/IOS cross-compilation

    * Add OSX/IOS cross-compilation test to Travis CI

    * Handle platforms that lack hwcap.h by falling back to ARMV8

    * Fix PROLOGUE for OSX/IOS
```

## Platform/toolchain

```console
$ uname -a
Darwin vostok 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64
$ xcodebuild -version
Xcode 11.3.1
Build version 11C504
$ clang --version
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ gfortran --version
GNU Fortran (Homebrew GCC 9.2.0_2) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

## Fix

```
diff --git a/common_arm64.h b/common_arm64.h
index 5951e1ee..a30580a7 100644
--- a/common_arm64.h
+++ b/common_arm64.h
@@ -118,9 +118,7 @@ static inline int blas_quickdivide(blasint x, blasint y){
        .text ;
        .p2align 2 ;
        .global REALNAME ;
-#ifndef __APPLE__
        .type   REALNAME, %function ;
-#endif
 REALNAME:
 .endm
```

**Comment by isuruf** [comment]
You need fixes from https://github.com/xianyi/OpenBLAS/pull/2424

**Comment by sethrj** [comment]
Blarg, I started debugging this last week and (of course) didn't have that patch. Thanks.

**Comment by sethrj** [comment]
Closing, but good to keep this issue as a record that openblas 0.3.8 does not work on apple intel platforms.
