### ISSUE TITLE
test_fork utest fails to build with GCC 4.7.2

### ISSUE THREAD

**Issue by Diazonium** [xianyi/OpenBLAS#1519]
So there is this HPC cluster where the newest GCC available is 4.7.2, and I have tried to build a fresh dev version of OpenBLAS. If threading is disabled it builds just fine, but with threading enabled the build of one of the utests fail. I suspect this is due to the ancient compilers/libraries/kernel present on the system. Older versions of OpenBLAS did not have this issue.
Log:
```
<snip>
gcc -O2 -DUTEST_CHECK -DSANITY_CHECK -DREFNAME=test_forkf_ -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=24 -DASMNAME=test_fork -DASMFNAME=test_fork_ -DNAME=test_fork_ -DCNAME=test_fork -DCHAR_NAME=\"test_fork_\" -DCHAR_CNAME=\"test_fork\" -I..   -c -o test_fork.o test_fork.c
In file included from test_fork.c:35:0:
/usr/include/sys/wait.h:116:22: error: unknown type name ‘__WAIT_STATUS’
In file included from test_fork.c:35:0:
/usr/include/sys/wait.h:169:23: error: unknown type name ‘__WAIT_STATUS’
/usr/include/sys/wait.h:179:38: error: unknown type name ‘__WAIT_STATUS’
test_fork.c: In function ‘__ctest_fork_safety_run’:
test_fork.c:109:13: warning: implicit declaration of function ‘wait’ [-Wimplicit-function-declaration]
test_fork.c:111:13: warning: implicit declaration of function ‘WEXITSTATUS’ [-Wimplicit-function-declaration]
make[1]: *** [test_fork.o] Error 1
<snip>
```

**Comment by martin-frbg** [comment]
Strange, this looks almost like an inconsistency within the system headers. What OS version is that ? You could try adding `#include <sys/types.h>` before the `#include <sys/wait.h>` in utest/test_fork.c though.

**Comment by Diazonium** [comment]
I am not 100% sure, but it looks like RHEL 5 or some derivative of it.

**Comment by Diazonium** [comment]
BTW, the default system compiler would be much older, I think GCC 4.1.2 or something like that, but the cluster has some sort of module system that allows users to change the versions of some software. I really do not know how that works, but I am using that to get the "cutting edge" 4.7.2 compilers instead of whatever prehistoric junk is the default.

**Comment by martin-frbg** [comment]
Could be that wait.h is supplied by the glibc headers so you would probably be stuck with some old junk in any case. (rpm -qf /usr/include/sys/wait.h should tell). Still maybe best to disable the fork utest for the next release, as there is still a chance it may hang on some of those systems where it can be built.

**Comment by Diazonium** [comment]
Running `rpm -qf /usr/include/sys/wait.h` outputs `glibc-headers-2.5-58`, not sure what that means, but it seems you are right about that guess.

**Comment by martin-frbg** [comment]
So a libc from about 12 years ago...makes one wonder how high performance (or just noise level) that HPC system is... can you try with the additional types.h ?

**Comment by Diazonium** [comment]
I think I managed to work around the issue by deleting the part in utests/Makefile, that builds test_fork. The build seems to have completed without errors.
As for the HPC part...well it certainly does have a lot of RAM and cores (~50 nodes, each node is a quad-socket with 48 Barcelona cores/node and 132 GB of RAM), quite old, but it would be still very useful if it had a modern software stack and a storage system that did not suck.

**Comment by martin-frbg** [comment]
Ok. I'll see if I can set up a VM with such an old system later to reproduce and fix this. At first glance the wait.h from the old glibc headers does not look that much different from the current one.

**Comment by jeromerobert** [comment]
#1523 did not fixed the issue. See #1787 for what I think to be the actual fix.
