### PR TITLE
Fix "Argument list too long" compilation error for Intel macOS

### LINKED ISSUE #5223: `cmake` build failure on x86_64 macOS 14 with `-DDYNAMIC_ARCH=ON` and `-DBUILD_STATIC_LIBS=ON`
The failure was seen in https://github.com/Homebrew/homebrew-core/pull/219339. It was caused by too many arguments (*.o files) being passed to `ar`.

Specifically, the `cmake` options used are
```sh
-DBUILD_SHARED_LIBS=ON
-DBUILD_STATIC_LIBS=ON
-DNUM_THREADS=64
-DTARGET=NEHALEM
-DDYNAMIC_ARCH=ON
```
The problematic `ar` call looks like
```sh
/usr/bin/ar qc lib/libopenblas.a interface/CMakeFiles/interface.dir/CMakeFiles/scopy.c.o interface/CMakeFiles/interface.dir/CMakeFiles/snrm2.c.o .......
```
which has over 1000000 characters, due to large amount of object files. And the error message is:
```
collect2: fatal error: posix_spawnp: Argument list too long
```

### PR DESCRIPTION
**Pull request by ywwry66**
Closes #5223. Tested on Homebrew's CI runners where OpenBLAS was built successfully with dynamic arch turned on.

### CODE REVIEW

**Comment by martin-frbg** [comment]
Thank you
